export enum actionTypes {
  CHANGE_ROUTE = 'CHANGE_ROUTE',
  USER_LOGOUT = 'USER_LOGOUT',
  LOGIN = 'LOGIN',
  CONFIRM = 'CONFIRM',
  CREATE_COMPANY = 'CREATE_COMPANY',
  GET_COMPANIES = 'GET_COMPANIES',
  GET_JOURNAL = 'GET_JOURNAL',
  GET_CASH = 'GET_CASH',
  GET_CAPITAL = 'GET_CAPITAL',
  GET_BANK = 'GET_BANK',
}
