name: Build and Test
on: [push]
jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependences
        run: yarn
#       - name: Run tests
#         run: npm test
